template: true
valuesFilePath: ./values.yml

resources:
  - name: setup_yarn
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https
      buildOn:
        commit: true

pipelines:
  - name: yarn_setup_test
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          RESOLVE_REPO: npm-virtual

    steps:
      - name: test_yarn
        type: Bash
        configuration:
          inputResources:
            - name: setup_yarn
          integrations:
            - name: "{{ .Values.cacheArtIntegration}}"
        execution:
          onStart:
            - task: jfrog/setup-node@v0.0.1
              id: setup_node
              input:
                version: "{{ .Values.nodeVersion }}"
          onExecute:
            - pushd $res_setup_yarn_resourcePath
            # Configure JFrog CLI
            - jfrog npmc --repo-resolve $RESOLVE_REPO
            # Install npm dependencies
            - jf npm install
            # Build task runnable script bundled with dependencies
            - npm run dist
            # create test coverage report
            - npx jest --coverage
            - popd
            # Run task
            - task: $res_setup_yarn_resourcePath
              id: setup_yarn_test
              input:
                version:
            - echo "setup yarn completed"
          onComplete:
            - echo "setup task template Test done!"
