repoPath: bhanurp/slack-pipe
mainBranch: master
gitIntegration: int_github_slack
artIntegration: int_default_artifactory
slackIntegration: int_slack_publish_task
tokenIntegration: int_slack_token
windowsNodePool:
nodeVersion: 18.12.1
cacheArtIntegration: pipelines-tasks-cache-virtual
